export const aliases: { [key: string]: string } = Object.freeze({
  ms: 'ms',
  millisec: 'ms',
  millisecond: 'ms',
  milliseconds: 'ms',
  msec: 'ms',
  s: 's',
  sec: 's',
  second: 's',
  seconds: 's',
  m: 'm',
  min: 'm',
  minute: 'm',
  minutes: 'm',
  h: 'h',
  hour: 'h',
  hours: 'h',
  d: 'd',
  day: 'd',
  days: 'd',
  w: 'w',
  week: 'w',
  weeks: 'w',
});
